name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./lar-em-ordem-api

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Configurar ambiente PHP (v8.5)
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
          extensions: mbstring, dom, fileinfo, pdo, pdo_sqlite
          tools: composer:v2
          coverage: none
      - name: Cache das Dependências do Composer
        uses: actions/cache@v4
        with:
          path: ~/.composer/cache
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Copiar .env de Teste
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Instalar Dependências do Composer
        run: composer install --prefer-dist --no-progress --no-interaction

      - name: Gerar Chave da Aplicação
        run: php artisan key:generate

      - name: Executar Migrações e Testes (PHPUnit)
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: ":memory:"
        run: php artisan test

  react-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./lar-em-ordem-frontend

    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Node.js (v22)
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./lar-em-ordem-frontend/package-lock.json

      - name: Instalar Dependências do NPM
        run: npm ci

      - name: Validar Build de Produção
        run: npm run build